# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update
apt-get install -y libffi-dev
apt-get install -y python3-venv
apt-get install -y python3-pip
pip3 install -r /vagrant/requirements.txt
SCRIPT

Vagrant.configure(2) do |config|

  # Not using ubuntu/xenial64 because of
  #  https://bugs.launchpad.net/cloud-images/+bug/1569237
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "waypoint-deployment-tools"
  config.ssh.forward_agent = true
  config.vm.post_up_message = "Run 'WAYPOINT_GITHUB_TOKEN=<whatever-it-is> python3 /vagrant/prepare_release.py' to start the release process"

  config.vm.provider "vmware_fusion" do |vmw|
    vmw.vmx["memsize"] = 512
    vmw.vmx["numvcpus"] = 4
    vmw.vmx["usb.present"] = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: $script
end
